DB_NAME = "defaultdb"
DEFAULT_ASSET_OPEN_DURATION = 4 # no of days


SESSIONSDB_HOST = "127.0.0.1"
SESSIONSDB_PORT = 6379
SESSIONSDB_PASSWD = None
SESSIONSDB_NO = 1

NESTED_REPLIES_ALLOWED = False

AUTO_APPROVAL = False
KARMA_BASED_APPROVAL = False
MIN_COMMENTS_REQUIRED_FOR_KARMA = 10
MIN_KARMA_REQUIRED_FOR_APPROVAL = 75 # in percent

DEFAULT_COMMENTS_FETCH_LIMIT = 20
DEFAULT_REPLIES_FETCH_LIMIT = 100
