DB_NAME = "defaultdb"
DEFAULT_ASSET_OPEN_DURATION = 4 # no of days


SESSIONSDB_HOST = "127.0.0.1"
SESSIONSDB_PORT = 6379
SESSIONSDB_PASSWD = None
SESSIONSDB_NO = 1

DEFAULT_COMMENTS_FETCH_LIMIT = 20
DEFAULT_REPLIES_FETCH_LIMIT = 100

MODERATION_POLICY = 2 # 1:Automatic, 2:Manual

SSO_API_URL = "http://localhost:9000/api/1.0/"

# Redis
TASKQ_HOST = "localhost"
TASKQ_PORT = 6379
TASKQ_DB = 1

EMAIL_NOTIFICATION = False

# SMTP
MD_HOST = ''
MD_PORT = 587
MD_USERNAME = ''
MD_KEY = ''

EMAIL_NOTIFICATION_SENDER = "example@example.com"
TEMPLATE_DIR = "app/templates"
ARTICLE_EMAIL_TEMPLATE_DIR = TEMPLATE_DIR + ""
ARTICLE_EMAIL_SUBJECT_PREFIX = ""
