DB_NAME = "defaultdb"
DEFAULT_ASSET_OPEN_DURATION = 4 # no of days


SESSIONSDB_HOST = "127.0.0.1"
SESSIONSDB_PORT = 6379
SESSIONSDB_PASSWD = None
SESSIONSDB_NO = 1

DEFAULT_COMMENTS_FETCH_LIMIT = 20
DEFAULT_REPLIES_FETCH_LIMIT = 100

MODERATION_POLICY = 2 # 1:Automatic, 2:Manual